/// Minimal app strings for top 25 GDP countries
/// ~30 key strings × 17 languages = ~510 translations
/// Estimated size: ~20-30KB
class AppStrings {
  static final Map<String, Map<String, String>> _strings = {
    // Premium / Paywall
    'upgrade_to_premium': {
      'en': 'Upgrade to Premium',
      'zh': '升级到高级版',
      'de': 'Upgrade auf Premium',
      'ja': 'プレミアムにアップグレード',
      'hi': 'प्रीमियम में अपग्रेड करें',
      'fr': 'Passer à Premium',
      'pt': 'Fazer Upgrade para Premium',
      'it': 'Passa a Premium',
      'ru': 'Перейти на Премиум',
      'es': 'Actualizar a Premium',
      'ko': '프리미엄으로 업그레이드',
      'id': 'Upgrade ke Premium',
      'nl': 'Upgraden naar Premium',
      'ar': 'الترقية إلى النسخة المتميزة',
      'tr': 'Premium\'a Yükselt',
      'pl': 'Przejdź na Premium',
      'sv': 'Uppgradera till Premium',
    },
    'premium_features': {
      'en': 'Premium Features',
      'zh': '高级功能',
      'de': 'Premium-Funktionen',
      'ja': 'プレミアム機能',
      'hi': 'प्रीमियम सुविधाएँ',
      'fr': 'Fonctionnalités Premium',
      'pt': 'Recursos Premium',
      'it': 'Funzionalità Premium',
      'ru': 'Премиум функции',
      'es': 'Características Premium',
      'ko': '프리미엄 기능',
      'id': 'Fitur Premium',
      'nl': 'Premium Functies',
      'ar': 'ميزات النسخة المتميزة',
      'tr': 'Premium Özellikler',
      'pl': 'Funkcje Premium',
      'sv': 'Premium Funktioner',
    },
    'restore_purchases': {
      'en': 'Restore Purchases',
      'zh': '恢复购买',
      'de': 'Käufe wiederherstellen',
      'ja': '購入を復元',
      'hi': 'खरीदारी बहाल करें',
      'fr': 'Restaurer les achats',
      'pt': 'Restaurar compras',
      'it': 'Ripristina acquisti',
      'ru': 'Восстановить покупки',
      'es': 'Restaurar compras',
      'ko': '구매 복원',
      'id': 'Pulihkan Pembelian',
      'nl': 'Aankopen herstellen',
      'ar': 'استعادة المشتريات',
      'tr': 'Satın Almaları Geri Yükle',
      'pl': 'Przywróć zakupy',
      'sv': 'Återställ köp',
    },
    'no_ads': {
      'en': 'No Ads',
      'zh': '无广告',
      'de': 'Keine Werbung',
      'ja': '広告なし',
      'hi': 'कोई विज्ञापन नहीं',
      'fr': 'Sans publicité',
      'pt': 'Sem anúncios',
      'it': 'Niente pubblicità',
      'ru': 'Без рекламы',
      'es': 'Sin anuncios',
      'ko': '광고 없음',
      'id': 'Tanpa Iklan',
      'nl': 'Geen advertenties',
      'ar': 'بدون إعلانات',
      'tr': 'Reklamsız',
      'pl': 'Bez reklam',
      'sv': 'Inga annonser',
    },
    'one_time_purchase': {
      'en': 'One-time purchase',
      'zh': '一次性购买',
      'de': 'Einmalkauf',
      'ja': 'ワンタイム購入',
      'hi': 'एक बार की खरीद',
      'fr': 'Achat unique',
      'pt': 'Compra única',
      'it': 'Acquisto una tantum',
      'ru': 'Разовая покупка',
      'es': 'Compra única',
      'ko': '일회성 구매',
      'id': 'Pembelian sekali',
      'nl': 'Eenmalige aankoop',
      'ar': 'شراء لمرة واحدة',
      'tr': 'Tek seferlik satın alma',
      'pl': 'Zakup jednorazowy',
      'sv': 'Engångsköp',
    },
    
    // Navigation & Actions
    'settings': {
      'en': 'Settings',
      'zh': '设置',
      'de': 'Einstellungen',
      'ja': '設定',
      'hi': 'सेटिंग्स',
      'fr': 'Paramètres',
      'pt': 'Configurações',
      'it': 'Impostazioni',
      'ru': 'Настройки',
      'es': 'Ajustes',
      'ko': '설정',
      'id': 'Pengaturan',
      'nl': 'Instellingen',
      'ar': 'الإعدادات',
      'tr': 'Ayarlar',
      'pl': 'Ustawienia',
      'sv': 'Inställningar',
    },
    'cancel': {
      'en': 'Cancel',
      'zh': '取消',
      'de': 'Abbrechen',
      'ja': 'キャンセル',
      'hi': 'रद्द करें',
      'fr': 'Annuler',
      'pt': 'Cancelar',
      'it': 'Annulla',
      'ru': 'Отмена',
      'es': 'Cancelar',
      'ko': '취소',
      'id': 'Batal',
      'nl': 'Annuleren',
      'ar': 'إلغاء',
      'tr': 'İptal',
      'pl': 'Anuluj',
      'sv': 'Avbryt',
    },
    'save': {
      'en': 'Save',
      'zh': '保存',
      'de': 'Speichern',
      'ja': '保存',
      'hi': 'सहेजें',
      'fr': 'Enregistrer',
      'pt': 'Salvar',
      'it': 'Salva',
      'ru': 'Сохранить',
      'es': 'Guardar',
      'ko': '저장',
      'id': 'Simpan',
      'nl': 'Opslaan',
      'ar': 'حفظ',
      'tr': 'Kaydet',
      'pl': 'Zapisz',
      'sv': 'Spara',
    },
    'delete': {
      'en': 'Delete',
      'zh': '删除',
      'de': 'Löschen',
      'ja': '削除',
      'hi': 'हटाएं',
      'fr': 'Supprimer',
      'pt': 'Excluir',
      'it': 'Elimina',
      'ru': 'Удалить',
      'es': 'Eliminar',
      'ko': '삭제',
      'id': 'Hapus',
      'nl': 'Verwijderen',
      'ar': 'حذف',
      'tr': 'Sil',
      'pl': 'Usuń',
      'sv': 'Ta bort',
    },
    'done': {
      'en': 'Done',
      'zh': '完成',
      'de': 'Fertig',
      'ja': '完了',
      'hi': 'पूर्ण',
      'fr': 'Terminé',
      'pt': 'Concluído',
      'it': 'Fatto',
      'ru': 'Готово',
      'es': 'Hecho',
      'ko': '완료',
      'id': 'Selesai',
      'nl': 'Klaar',
      'ar': 'تم',
      'tr': 'Bitti',
      'pl': 'Gotowe',
      'sv': 'Klar',
    },
    'close': {
      'en': 'Close',
      'zh': '关闭',
      'de': 'Schließen',
      'ja': '閉じる',
      'hi': 'बंद करें',
      'fr': 'Fermer',
      'pt': 'Fechar',
      'it': 'Chiudi',
      'ru': 'Закрыть',
      'es': 'Cerrar',
      'ko': '닫기',
      'id': 'Tutup',
      'nl': 'Sluiten',
      'ar': 'إغلاق',
      'tr': 'Kapat',
      'pl': 'Zamknij',
      'sv': 'Stäng',
    },
    'continue': {
      'en': 'Continue',
      'zh': '继续',
      'de': 'Weiter',
      'ja': '続ける',
      'hi': 'जारी रखें',
      'fr': 'Continuer',
      'pt': 'Continuar',
      'it': 'Continua',
      'ru': 'Продолжить',
      'es': 'Continuar',
      'ko': '계속',
      'id': 'Lanjutkan',
      'nl': 'Doorgaan',
      'ar': 'متابعة',
      'tr': 'Devam et',
      'pl': 'Kontynuuj',
      'sv': 'Fortsätt',
    },
    
    // Common UI
    'loading': {
      'en': 'Loading...',
      'zh': '加载中...',
      'de': 'Wird geladen...',
      'ja': '読み込み中...',
      'hi': 'लोड हो रहा है...',
      'fr': 'Chargement...',
      'pt': 'Carregando...',
      'it': 'Caricamento...',
      'ru': 'Загрузка...',
      'es': 'Cargando...',
      'ko': '로딩 중...',
      'id': 'Memuat...',
      'nl': 'Laden...',
      'ar': 'جاري التحميل...',
      'tr': 'Yükleniyor...',
      'pl': 'Ładowanie...',
      'sv': 'Laddar...',
    },
    'error': {
      'en': 'Error',
      'zh': '错误',
      'de': 'Fehler',
      'ja': 'エラー',
      'hi': 'त्रुटि',
      'fr': 'Erreur',
      'pt': 'Erro',
      'it': 'Errore',
      'ru': 'Ошибка',
      'es': 'Error',
      'ko': '오류',
      'id': 'Kesalahan',
      'nl': 'Fout',
      'ar': 'خطأ',
      'tr': 'Hata',
      'pl': 'Błąd',
      'sv': 'Fel',
    },
    'retry': {
      'en': 'Retry',
      'zh': '重试',
      'de': 'Wiederholen',
      'ja': '再試行',
      'hi': 'पुनः प्रयास करें',
      'fr': 'Réessayer',
      'pt': 'Tentar novamente',
      'it': 'Riprova',
      'ru': 'Повторить',
      'es': 'Reintentar',
      'ko': '다시 시도',
      'id': 'Coba lagi',
      'nl': 'Opnieuw proberen',
      'ar': 'إعادة المحاولة',
      'tr': 'Tekrar dene',
      'pl': 'Spróbuj ponownie',
      'sv': 'Försök igen',
    },
    
    // Empty States
    'no_items': {
      'en': 'No items',
      'zh': '没有项目',
      'de': 'Keine Elemente',
      'ja': '項目がありません',
      'hi': 'कोई आइटम नहीं',
      'fr': 'Aucun élément',
      'pt': 'Nenhum item',
      'it': 'Nessun elemento',
      'ru': 'Нет элементов',
      'es': 'Sin elementos',
      'ko': '항목 없음',
      'id': 'Tidak ada item',
      'nl': 'Geen items',
      'ar': 'لا توجد عناصر',
      'tr': 'Öğe yok',
      'pl': 'Brak elementów',
      'sv': 'Inga objekt',
    },
    'get_started': {
      'en': 'Get Started',
      'zh': '开始使用',
      'de': 'Loslegen',
      'ja': '始める',
      'hi': 'शुरू करें',
      'fr': 'Commencer',
      'pt': 'Começar',
      'it': 'Inizia',
      'ru': 'Начать',
      'es': 'Empezar',
      'ko': '시작하기',
      'id': 'Mulai',
      'nl': 'Aan de slag',
      'ar': 'ابدأ',
      'tr': 'Başla',
      'pl': 'Rozpocznij',
      'sv': 'Kom igång',
    },
    
    // Permissions
    'allow': {
      'en': 'Allow',
      'zh': '允许',
      'de': 'Erlauben',
      'ja': '許可',
      'hi': 'अनुमति दें',
      'fr': 'Autoriser',
      'pt': 'Permitir',
      'it': 'Consenti',
      'ru': 'Разрешить',
      'es': 'Permitir',
      'ko': '허용',
      'id': 'Izinkan',
      'nl': 'Toestaan',
      'ar': 'سماح',
      'tr': 'İzin ver',
      'pl': 'Zezwól',
      'sv': 'Tillåt',
    },
    'deny': {
      'en': 'Deny',
      'zh': '拒绝',
      'de': 'Ablehnen',
      'ja': '拒否',
      'hi': 'अस्वीकार करें',
      'fr': 'Refuser',
      'pt': 'Negar',
      'it': 'Nega',
      'ru': 'Отклонить',
      'es': 'Denegar',
      'ko': '거부',
      'id': 'Tolak',
      'nl': 'Weigeren',
      'ar': 'رفض',
      'tr': 'Reddet',
      'pl': 'Odmów',
      'sv': 'Neka',
    },
  };

  /// Get translation for key and language
  static String? get(String key, String languageCode) {
    return _strings[key]?[languageCode];
  }

  /// Check if key exists
  static bool hasKey(String key) => _strings.containsKey(key);

  /// Get all available keys
  static List<String> get keys => _strings.keys.toList();
}
